name: Run tests on commit
on:
  push:
    branches: ['main']
    paths:
      - 'crates/**/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: 0.11.0

    - name: Run tests
      run: |
        nargo test
    - name: Get constraint size
      run: |
        nargo info --package chacha20_example