name: Run tests on commit
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: 0.11.0
        
    - name: Run tests
      run: |
        nargo test